apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-1
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: pod-1
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3