apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.application.name}}
  name: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: frontend-example-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-example-1
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: frontend-example-1
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources: {}
        ports:
          - containerPort: 3080 