apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    run: frontend-example-1
spec:
  ports:
  - port: 3080
    protocol: TCP
  selector:
    app: frontend-example-1
  type: NodePort